### ISSUE TITLE
Failure to setup Multi server with OPN as LAPI

### ISSUE THREAD

**Issue by cookiemonsteruk** [crowdsecurity/opnsense-plugin-crowdsec#23]
OPNSense plugin v0.0.7
OPN v 22.1

I am unable to follow the multi server guide at https://crowdsec.net/blog/multi-server-setup/
After changing the ip from 127.0.0.1 to OPNSense's LAN ip i.e 192.168.5.1 in both /usr/local/etc/crowdsec/config.yaml and /usr/local/etc/crowdsec/local_api_credentials.yaml and restarting crowdsec with "sudo service crowdsec restart", the following happens:
1. The service fails to restart. It notifies the address is in use.
time="06-03-2022 21:46:45" level=fatal msg="listen tcp 192.168.5.1:8080: bind: address already in use"
According to "sockstat" that is accurate:
```
% sudo sockstat -4
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
root     crowdsec   44653 9  tcp4   127.0.0.1:6060        *:*
root     crowdsec   44653 12 tcp4   127.0.0.1:8080        *:*
```
2. After reverting the change to both yaml files and re-issuing a crowdsec restart, the service starts successfully as expected but in the Plugin UI the bouncer never comes back as running in the top "overview" banner. 
The bouncer tab however shows it as running and a cscli check also confirms it runnig. 
```
% sudo cscli bouncers list
--------------------------------------------------------------------------------------------------------------------------------------------------------
 NAME                          IP ADDRESS  VALID  LAST API PULL         TYPE                       VERSION                                              
--------------------------------------------------------------------------------------------------------------------------------------------------------
 cs-firewall-bouncer-IDIdID  127.0.0.1   ✔️      2022-03-06T21:41:52Z  crowdsec-firewall-bouncer  v0.0.23-rc2-bc4bb1d531d47ad94ead2dce3a11f6391b1e8619 
--------------------------------------------------------------------------------------------------------------------------------------------------------

```
It makes it unclear if the problem is only cosmetic.

**Comment by mmetc** [comment]
You should also update the api url in /usr/local/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
and restart it too, or use "configctl crowdsec reconfigure" which applies any configuration changes and restarts both

**Comment by cookiemonsteruk** [comment]
> You should also update the api url in /usr/local/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
> and restart it too, or use "configctl crowdsec reconfigure" which applies any configuration changes and restarts both
I assume this is what I should try post rollback and show a green tick again? How do I restart the bouncer. A search ctrl-K in the docs didn't find it. I'd like to try that first if possible.

**Comment by cookiemonsteruk** [comment]
It is odd. It succeeded on the  next attempt;

```
@OPNsense:~ % sudo service crowdsec_firewall restart
crowdsec_firewall not running? (check /var/run/crowdsec_firewall.pid).
@OPNsense:~ % ls -al /var/run/crow*
-rw-------  1 root  wheel  5 Mar  6 22:41 /var/run/crowdsec.pid
-rw-------  1 root  wheel  5 Mar  7 16:17 /var/run/crowdsec_firewall.pid
@OPNsense:~ % sudo service crowdsec_firewall start
Password:
crowdsec_firewall already running?  (pid=42294).
penguin@OPNsense:~ % sudo service crowdsec_firewall status
crowdsec_firewall is running as pid 42294.
penguin@OPNsense:~ % sudo service crowdsec_firewall restart
Stopping crowdsec_firewall.
Waiting for PIDS: 42294.
@OPNsense:~ % 
```
And has now resolved point 2. in this report. Thank you.!

If I could ask about point 1. :
Is that a defect ?

**Comment by mmetc** [comment]
> It is odd. It succeeded on the next attempt;

Not odd, just a decisions the developers took. Service stop will give you an error if the service has already been stopped, and the same goes for start/restart.

> If I could ask about point 1. :
> Is that a defect ?

I don't see the process using 192.168.5.1:8080 - which is a very different port than the 127.0.0.1:8080 which you listed. I know it's in use because the crowdsec log told you so. If you have a plugin, NAT or anything else there, please switch both crowdsec and the bouncer to a free number.

**Comment by cookiemonsteruk** [comment]
Actually in this case is the same because OPNSense has a LAN ip of 192.168.5.1 and there's nothing apart from crowdsec using port 8080 on it. 
Remember  OPN being a firewall, 127.0.0.1 being the loopback of it, when trying to set opn as lapi, then it needs to switch from the loopback to the lan address.
As you can see from the first comment, crowdsec is binding to that port 8080 already.
I'm going to reboot and start again.

**Comment by cookiemonsteruk** [comment]
Rebooted and yes you are right. I do have LAN:8080 occupied by another service I had forgotten about.
I'm going to try switching to another port as suggested and report back.

**Comment by cookiemonsteruk** [comment]
I've now used port 8081 but I can't register a machine to it.
As suggested I modified the three files config.yaml, local_api_credentials.yaml and crowdsec-firewall-bouncer.yaml
Then I ran a "configctl crowdsec reconfigure"  followed by a "service crowdsec_firewall start".
```
@OPNsense:~ % cat /usr/local/etc/crowdsec/config.yaml
api:
  client:
    credentials_path: /usr/local/etc/crowdsec/local_api_credentials.yaml
    insecure_skip_verify: false
  server:
    listen_uri: 192.168.5.1:8081
    log_level: info
    online_client:
      credentials_path: /usr/local/etc/crowdsec/online_api_credentials.yaml
    profiles_path: /usr/local/etc/crowdsec/profiles.yaml
common:
  daemonize: true
  log_dir: /var/log/crowdsec
  log_level: info
  log_media: file
  pid_dir: /var/run/
  working_dir: .
config_paths:
  config_dir: /usr/local/etc/crowdsec/
  data_dir: /var/db/crowdsec/data/
  hub_dir: /usr/local/etc/crowdsec/hub/
  index_path: /usr/local/etc/crowdsec/hub/.index.json
  notification_dir: /usr/local/etc/crowdsec/notifications/
  plugin_dir: /usr/local/lib/crowdsec/plugins/
  simulation_path: /usr/local/etc/crowdsec/simulation.yaml
crowdsec_service:
  acquisition_dir: /usr/local/etc/crowdsec/acquis.d/
  acquisition_path: /usr/local/etc/crowdsec/acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  db_path: /var/db/crowdsec/data/crowdsec.db
  flush:
    max_age: 7d
    max_items: 5000
  log_level: info
  type: sqlite
plugin_config:
  group: nogroup
  user: nobody
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
```
```
@OPNsense:~ % sudo cat /usr/local/etc/crowdsec/local_api_credentials.yaml

#url: http://127.0.0.1:8080
url: http://192.168.5.1:8081
login: {redacted}
password: {redacted}
```
```
@OPNsense:~ % sudo cat /usr/local/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
api_key: {redacted}
api_url: http://localhost:8081/
blacklists_ipv4: crowdsec_blacklists
blacklists_ipv6: crowdsec6_blacklists
daemonize: true
deny_action: DROP
deny_log: false
disable_ipv6: false
iptables_chains:
- INPUT
log_dir: /var/log/crowdsec
log_level: info
log_mode: file
mode: pf
pf:
  anchor_name: ''
pid_dir: /var/run/
supported_decisions_types:
- ban
update_frequency: 10s

```
But the bouncer seems to crash after a little time, maybe a few minutes. This is locally on OPN of course:
In /var/log/crowdsec/crowdsec-firewall-bouncer.log

```
time="07-03-2022 22:37:40" level=info msg="backend type : pf"
time="07-03-2022 22:37:40" level=info msg="pf table clean-up: /sbin/pfctl -t crowdsec_blacklists -T flush"
time="07-03-2022 22:37:40" level=info msg="Checking pf table: crowdsec_blacklists"
time="07-03-2022 22:37:40" level=info msg="pf initiated for ipv4"
time="07-03-2022 22:37:40" level=info msg="pf table clean-up: /sbin/pfctl -t crowdsec6_blacklists -T flush"
time="07-03-2022 22:37:40" level=info msg="Checking pf table: crowdsec6_blacklists"
time="07-03-2022 22:37:40" level=info msg="pf initiated for ipv6"
time="07-03-2022 22:37:40" level=info msg="Processing new and deleted decisions . . ."
time="07-03-2022 22:38:10" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8081: i/o timeout"
time="07-03-2022 22:38:10" level=fatal msg="Get \"http://localhost:8081/v1/decisions/stream?startup=true\": dial tcp 127.0.0.1:8081: i/o timeout"
```
And perhaps understandably the registration of the remote machine fails with a timeout:
The firewall is not getting it the way, I can see the call coming in but no reply. I assume is because the service has crashed
```
@OPNsense:~ % sudo service crowdsec_firewall status
Password:
crowdsec_firewall is not running.
```

```
@mars:/tmp$ sudo cscli lapi register -u http://192.168.5.1:8081
[sudo] password for me: 
FATA[07-03-2022 10:38:54 PM] api client register: api register (http://192.168.5.1:8081/) : Post "http://192.168.5.1:8081/v1/watchers": dial tcp 192.168.5.1:8081: i/o timeout: Post "http://192.168.5.1:8081/v1/watchers": dial tcp 192.168.5.1:8081: i/o timeout 
```
What have I done wrong please?
